### DISCUSSION TITLE
Adding external database IDs for original games

### DISCUSSION THREAD

**Discussion by ju5** [opengaming/osgameclones#3092] [Ideas]
What about adding fields for game database IDs (like IGDB, MobyGames, TheGamesDB)? Here's an example:
```yaml
- name: Doom
  external:
    wikipedia: Doom
    igdb: doom    # https://www.igdb.com/games/doom
    mobygames: 1168    # https://www.mobygames.com/game/1068/
    thegamesdb: 745    # https://thegamesdb.net/game.php?id=745
  meta: ...
```
This could work for most entries (except maybe tools/game series). With these IDs, we could use the databases' APIs to pull game metadata automatically.
