### ISSUE TITLE
Add TekWar

### ISSUE THREAD

**Issue by CommonLoon102** [opengaming/osgameclones#1030]
```
name: TekWar
names:
- William Shatner's TekWar
external:
  wikipedia: 'https://en.wikipedia.org/wiki/Tekwar_(game)'
platform:
- DOS
meta:
  genre:
  - FPS

```
