### ISSUE TITLE
Add Witchaven

### ISSUE THREAD

**Issue by CommonLoon102** [opengaming/osgameclones#1031]
```
name: Witchaven
external:
  wikipedia: 'https://en.wikipedia.org/wiki/Witchaven'
platform:
- DOS
meta:
  genre:
  - FPS
  - RPG
  theme:
  - Medieval

```
