### ISSUE TITLE
Add S.T.A.L.K.E.R. and OpenXRay

### ISSUE THREAD

**Issue by myCrack** [opengaming/osgameclones#1127]
![...](https://user-images.githubusercontent.com/6609131/91668987-782c7a00-eb3b-11ea-931a-22bb34c61125.png)

```yaml
name: OpenXRay
originals:
- S.T.A.L.K.E.R.
type: remake
repo: 'https://github.com/OpenXRay/xray-16'
development: very active
status: playable
multiplayer:
- Online
- LAN
content: commercial
lang:
- C++
- Lua
framework:
- OpenXRay
- X-Ray
- SDL2
- DirectX
- OpenGL
- Open Dynamics Engine
license:
- BSD
info: 'Crossplatform implementation of the S.T.A.L.K.E.R. games - Windows, linux etc.'
images:
- 'https://github.com/OpenXRay/xray-16/blob/xd_dev/OpenXRayCover.png'
video:
  youtube: Alr9YQv2JWQ
```

![...](https://user-images.githubusercontent.com/6609131/91669188-4c11f880-eb3d-11ea-8140-72a0a7e4dec3.png)
```yaml
name: S.T.A.L.K.E.R.
names:
- Сталкер
external:
  wikipedia: S.T.A.L.K.E.R.
platform:
- Windows
meta:
  genre:
  - FPS
  subgenre:
  - Survival
  theme:
  - Alternate Historical
  - Fantasy
  - Horror
  - Modern Military
  - Post-Apocalyptic
  - Sci-Fi
```
