### ISSUE TITLE
Add Columns

### ISSUE THREAD

**Issue by dgengin** [opengaming/osgameclones#1235]
```yaml
name: Columns
originals:
- Columns
type: clone
repo: 'https://github.com/dgengin/Columns'
development: active
status: playable
content: commercial
lang:
- C++
framework:
- SFML
license:
- Zlib
images:
- >-
  https://user-images.githubusercontent.com/20025614/103457653-fcb12400-4cf8-11eb-8552-1ab5f46a8450.png
```
