### ISSUE TITLE
Add Diabolika

### ISSUE THREAD

**Issue by dgengin** [opengaming/osgameclones#1236]
```yaml
name: Diabolika
originals:
- Diabolika 2
type: clone
repo: 'https://github.com/dgengin/Diabolika'
development: complete
status: playable
content: commercial
lang:
- C++
framework:
- SFML
license:
- Zlib
images:
- >-
  https://user-images.githubusercontent.com/20025614/103456786-56155500-4cf1-11eb-8911-954eb57fc886.png

```
