### ISSUE TITLE
Add Memoria

### ISSUE THREAD

**Issue by Albeoris** [opengaming/osgameclones#1341]
```yaml
name: Memoria
originals:
- Final Fantasy IX
type: remake
repo: 'https://github.com/Albeoris/Memoria'
development: complete
status: playable
content: commercial
lang:
- 'C#'
framework:
- Unity
license:
- MIT
info: 'Reimplementation of the game engine in C#.'
updated: '2021-06-18'
video:
  youtube: cU4T3GSIjxs

```
