### ISSUE TITLE
Add Stone Kingdoms

### ISSUE THREAD

**Issue by evgenipetrov9** [opengaming/osgameclones#1717]
- Game:  
```yaml
name: Stone Kingdoms
originals:
- Stronghold
type: remake
repo: 'https://gitlab.com/stone-kingdoms/stone-kingdoms'
development: very active
status: semi-playable
content: free
lang:
- Lua
framework:
- love2d
license:
- Apache
info: >-
  An isometric real-time strategy remake of the original Stronghold game by
  Firefly Studios
updated: '2022-05-18'
images:
- >-
  https://gitlab.com/stone-kingdoms/stone-kingdoms/-/raw/master/assets/other/screenshot_1.jpg
```

- Original (already exists but this is an update):  
```yaml
name: Stronghold
external:
  website: 'https://fireflyworlds.com/games/stronghold/'
  wikipedia: 'https://en.wikipedia.org/wiki/Stronghold_(2001_video_game)'
platform:
- Windows
meta:
  genre:
  - Real-Time Strategy
  - Simulation
  - Strategy
  subgenre:
  - City Building
  theme:
  - Medieval
```
