### ISSUE TITLE
Update some existing titles as `type: official`

### ISSUE THREAD

**Issue by kparal** [opengaming/osgameclones#1754]
When going through the database, I believe I found a few titles which could use the new `type: official` tag (more investigation needed, I looked very quickly):

```yaml
- name: GloomAmiga
  originals:
  - Gloom
  type: remake
  repo: 'https://github.com/earok/GloomAmiga'
  development: complete
  status: playable
  content: commercial
  langs:
  - Assembly
  licenses:
  - Unlicense
  info: official source code release
  updated: '2021-12-25'
  video:
    youtube: BELCO16pwNM
```

```yaml
- name: OpenLiero
  feed: https://twitter.com/lieroofficial
  langs:
  - C++
  licenses:
  - Custom
  content: free
  development: halted
  status: playable
  multiplayer:
  - Split-screen
  frameworks:
  - SDL
  originals:
  - Liero
  repo: https://github.com/gliptic/liero
  type: remake
  url: http://www.liero.be/
  updated: 2019-04-09
  info: Perfect clone of 1.33; a.k.a. Liero 1.36. License information at http://www.liero.be/licenses/135/licenses.txt
  images:
  - https://happypenguin.altervista.org/screenshots/openliero.png
  video:
    youtube: BzvWW_SzZvk
```

We should probably also add official versions of Little Big Adventure 1+2 source code (frozen in time), to go alongside the community versions already present in OSGC:
https://github.com/2point21/lba1-classic
https://github.com/2point21/lba2-classic
