### ISSUE TITLE
Add [Free Hero Mesh]

### ISSUE THREAD

**Issue by zzo38** [opengaming/osgameclones#1760]
Note:

- I am not sure that I had done it properly. If it is not properly, then please fix it.

- I am using Fossil and not Git for my own projects, so the repo link is not GitHub.

- I don't know if the `type` is supposed to say `remake` or `clone`. I rewrote the game engine to be able to run the Hero Hearts games (which you will still need to purchase, if you want to play the Hero Hearts game) but also then I added many new feature it is not only a game engine clone but also is a new game engine that you can make your own puzzles too, even if you do not have the original game.

New game
```yaml
- name: Free Hero Mesh
  originals:
  - Hero Hearts
  type: clone
  repo: https://chiselapp.com/user/zzo38/repository/freeheromesh/
  url: http://zzo38computer.org/freeheromesh/
  development: active
  status: playable
  content: swappable
  frameworks:
  - SDL
  licenses:
  - PD
  info: 'A clone of MESH:Hero Hearts engine but also many new and improved features that the original game engine does not have.'
  updated: 2022-07-01
```

Original game
```yaml
- name: Hero Hearts
  external:
    website: https://www.kaser.com/mesh.html
  names:
  - 'MESH:Hero Hearts'
  platforms:
  - Windows
  - OSX
  meta:
    genres:
    - Puzzle
```
