### ISSUE TITLE
Add TrinityCore

### ISSUE THREAD

**Issue by danielsreichenbach** [opengaming/osgameclones#2397]
TrinityCore is a clone of the World of Warcraft servers for older game versions, allowing players to relive the original game.

User are required to own a copy of the original game to play.

```yaml
name: TrinityCore
originals:
- World of Warcraft
type: clone
repo: 'https://github.com/TrinityCore/TrinityCore'
url: 'https://www.trinitycore.org/'
development: complete
status: playable
multiplayer:
- Local
- Online
- LAN
content: commercial
langs:
- C++
licenses:
- GPL2
updated: '2023-12-27'
```
