### ISSUE TITLE
Add CTR-ModSDK

### ISSUE THREAD

**Issue by ju5** [opengaming/osgameclones#3052]
```
name: CTR-ModSDK
originals:
- Crash Team Racing
type: tool
repo: 'https://github.com/CTR-tools/CTR-ModSDK'
development: very active
status: N/A
content: commercial
langs:
- C
- C++
licenses:
- As-is
info: >-
  A modding toolkit to create mods for Crash Team Racing in C. This SDK
  also houses an effort to fully decompile and reverse-engineer CTR in C.
added: '2025-06-01'
updated: '2025-06-01'
video:
  youtube: V9QlFzSVDAU
```

```
name: Crash Team Racing
external:
  website: 'https://www.mobygames.com/game/ctr-crash-team-racing'
  wikipedia: Crash_Team_Racing
platforms:
- PlayStation
- PlayStation 3
- PlayStation Vita
- PSP
meta:
  genres:
  - Racing
  themes:
  - Motorsports
```
