### ISSUE TITLE
Add Tanks of Freedom

### ISSUE THREAD

**Issue by drummyfish** [opengaming/osgameclones#544]
New game

```yaml
- name: Tanks of Freedom
  remakes: []
  clones: [Advance Wars]
  repo: https://github.com/w84death/Tanks-of-Freedom
  url: http://tof.p1x.in
  feed:
  development:
  status: active
  multiplayer: []
  lang: []
  framework: [Godot]
  license: MIT
  content:
  info:
  updated:
  images: https://camo.githubusercontent.com/c9533920a76426abadae6282a17fee964a31ad34/687474703a2f2f746f662e7031782e696e2f6173736574732f73637265656e312e6a7067
    -
  video:
    youtube:
    vimeo:
```
