### ISSUE TITLE
Add 1oom, a Master of Orion clone

### ISSUE THREAD

**Issue by KilgoreTroutMaskReplicant** [opengaming/osgameclones#557]
1oom is a clone of the classic DOS game "Master of Orion" (MicroProse, 1993).

```yaml
- name: 1oom
  remakes: []
  clones: [Master of Orion]
  repo: https://github.com/KilgoreTroutMaskReplicant/1oom.git
  url: https://kilgoretroutmaskreplicant.github.io/1oom/
  feed:
  development: https://github.com/KilgoreTroutMaskReplicant/1oom
  status: playable but buggy
  multiplayer: []
  lang: []
  framework: []
  license: GPLv2
  content:
  info:
  updated:
  images:
    -
  video:
    youtube:
    vimeo:
```
