### ISSUE TITLE
Add OpenDrakan

### ISSUE THREAD

**Issue by pmatulka** [opengaming/osgameclones#563]
OpenDrakan

```yaml
- name: OpenDrakan
  remakes: [Drakan: Order of the Flame]
  clones: []
  repo: https://github.com/Zalasus/opendrakan
  url: 
  feed: 
  development: Active
  status: Unplayable
  multiplayer: []
  lang: [C++]
  framework: []
  license: GPL3
  content: Open
  info: 
  updated: 2018-05-19, 15:04 CEST
  images: 
  video:
    youtube:
    vimeo:
```
