### ISSUE TITLE
Add OpenD2

### ISSUE THREAD

**Issue by pmatulka** [opengaming/osgameclones#564]
OpenD2

```yaml
- name: OpenD2
  remakes: [Diablo II]
  clones: []
  repo: https://github.com/eezstreet/OpenD2
  url:
  feed:
  development: Sporadic
  status: Unplayable
  multiplayer: []
  lang: [C, C++]
  framework: []
  license: GPL3
  content: Open
  info:
  updated: 2018-04-03, 02:15 CEST
  images: ![Diablo II Main Menu in OpenD2](https://i.imgur.com/RFNbRiT.png)
  video:
    youtube:
    vimeo:
```
