### ISSUE TITLE
OldScool RuneScape

### ISSUE THREAD

**Issue by IanWONeill** [opengaming/osgameclones#582]
New game

```yaml
name:           VirtueOS     # Name of clone/remake (required)
remakes:        OldSchool RuneScape      # Name reference to original game(s) that this game remakes
clones:         OldSchool RuneScape      # Name reference to original game(s) that this game clones
repo:           http://github.com/IanWONeill/VirtueOS/     # Link to source code
url:            https://rune-status.net/     # Link to website
development:    active       # One of: complete, very active, active, sporadic, halted
status:         semi-playable       # One of: playable, semi-playable, unplayable
multiplayer:    Online       # Any of: Online, LAN, Split-screen, Co-op, Hotseat, Matchmaking
lang:           Java      # List of programming languages used
framework:      Netty.io      # List of engines/tools used
content:        open     # One of: commercial, free, open, swappable*
info:           able to login, walk arround, etc.     # Miscellaneous notes about the game
updated:        23/06/2018     # Date when game was added or updated
```
