### ISSUE TITLE
Status per original

### ISSUE THREAD

**Issue by tzizi** [opengaming/osgameclones#596]
Some remakes implement multiple games to various degrees of completion (ScummVM being the most obvious example, but there are others as well). Some of the games are playable, while others might be unplayable or semi-playable

My suggestion is something like this (using the format in #587):

```
  originals:
    - name: Game1
      status: playable
    - name: Game2
      status: semi-playable
```

For games that reimplement assets, it would also allow for specifying different levels of completion there as well.
