### ISSUE TITLE
Star Wars Jedi Knight: Dark Forces II

### ISSUE THREAD

**Issue by wobakj** [opengaming/osgameclones#618]
New game

```yaml
- name:gorc
  type: remake
  originals: [Star Wars Jedi Knight: Dark Forces II]
  repo: https://github.com/jdmclark/gorc
  url: https://github.com/jdmclark/gorc
  feed:
  development: sporadic
  status: semi-playable
  lang: [C++]
  framework: []
  license: Apache 2
  content: commercial
  info:
  multiplayer: []
  updated: 2018-8031
  images:
    -
  video:
    youtube:
    vimeo:
```
