### ISSUE TITLE
Kick Off

### ISSUE THREAD

**Issue by ssenegas** [opengaming/osgameclones#622]
New game

```yaml
- name: Open Kick Off
  type: remake
  originals: [Kick Off]
  repo: https://github.com/ssenegas/kickoff
  url: 
  feed:
  development: active
  status: semi playable
  multiplayer: []
  lang: [Java]
  framework: [libGDX]
  license: Apache License 2.0
  content:
  info:
  updated: May 1, 2018
  images: https://user-images.githubusercontent.com/9662172/39470980-0051a248-4d41-11e8-9a60-182320e25b57.PNG
    -
  video:
    youtube:
    vimeo:
```
