### ISSUE TITLE
OpenDominion

### ISSUE THREAD

**Issue by WaveHack** [opengaming/osgameclones#630]
Hi! I'd like to submit my project OpenDominion, a remake of Kamikaze Games Inc,'s [Dominion](http://web.archive.org/web/20110902061006/http://www.kamikazegames.com:80/dominion/).

```yaml
- name: OpenDominion
  type: remake
  originals: [Dominion]
  repo: https://github.com/WaveHack/OpenDominion
  url: https://opendominion.net
  feed: N/A
  development: active
  status: playable
  multiplayer: [Online]
  lang: [PHP, HTML, CSS, JavaScript]
  framework: [Laravel]
  license: MIT
  content: open
  info: The project is a text-based PBBG (Persistant Browser-Based Game) played in the web browser on both desktop and mobile.
  updated: 
  images:
    - https://i.imgur.com/BNayAx7.png
    - https://i.imgur.com/zVEcuVy.png
```

New entry for originals:

```yaml
- name: Dominion
  names: [Dominion Classic]
  platform: Web (new)
  meta:
    genre: [TBS, Strategy]
    subgenre: [Text-Based (new), Turn-Based Strategy]
    theme: [Fantasy]
```
