### ISSUE TITLE
Add openmom

### ISSUE THREAD

**Issue by rtentser** [opengaming/osgameclones#631]
```
- name: openmom
  lang: C++
  development: active
  originals:
  - Master of Magic
  repo: https://github.com/Jakz/openmom
  type: remake
  updated: 2018-10-11
```
