### ISSUE TITLE
Remove RPG genre from Lionheart

### ISSUE THREAD

**Issue by romatthe** [opengaming/osgameclones#637]
The original Amiga game `Lionheart` is labeled as `RPG` and `Action`. I don't really see how it's an RPG, plus this does create some confusion with the game `Lionheart: Legacy of the Crusader` by Reflexive Entertainment, which is an actual (Action) RPG. I'd recommend changing it to Action/Platform:

```yaml
- name: Lionheart
  external:
    wikipedia: Lionheart (video game)
  meta:
    genre:
    - Platform
    - Action
```
