### ISSUE TITLE
Add Remc2

### ISSUE THREAD

**Issue by turican0** [opengaming/osgameclones#658]
New game

```yaml
- name: REMC2
  type: # remake
  originals: [Magic Carpet 2: The Netherworlds]
  repo: https://github.com/turican0/remc2
  url: https://github.com/turican0/remc2/wiki
  development: # very active
  status: # unplayable
  lang: [english,deutsch,español,français,italiano,svenska,czech]
  framework: [SDL2]
  license: GNU General Public License v3.0
```
