### ISSUE TITLE
There are no target Shooting games: Like Police trainer, Shooting Gallery,  Shooting Arcade, Sharpshooter...

### ISSUE THREAD

**Issue by bteddy1** [opengaming/osgameclones#669]
New game

```yaml
- name:
  type: # One of: remake, clone
  originals: []
  repo:
  url:
  feed:
  development: # One of: complete, very active, active, sporadic, halted
  status: # One of: playable, semi-playable, unplayable
  multiplayer: []
  lang: []
  framework: []
  license:
  content: # One of: commercial, free, open, swappable*
  info:
  updated: # insert current date
  images:
    -
  video:
    youtube: # YouTube video ID
    vimeo: # Vimeo video ID
```
