### ISSUE TITLE
Open-Portal should be added to the list of Portal clones.

### ISSUE THREAD

**Issue by SamyBencherif** [opengaming/osgameclones#693]
New game. Not my project but looks pretty darn good!

https://github.com/lpuglia/Open-Portal
```yaml
- name: Open-Portal
  type: clone
  originals: []
  repo: https://github.com/lpuglia/Open-Portal
  url: https://github.com/lpuglia/Open-Portal
  feed:
  development: active # One of: complete, very active, active, sporadic, halted
  status: playable # One of: playable, semi-playable, unplayable
  multiplayer: []
  lang: [C]
  framework: []
  license:
  content: # One of: commercial, free, open, swappable*
  info:
  updated: # insert current date
  images:
    -
  video:
    youtube: http://www.youtube.com/watch?v=tqqeUCzWcdQ# YouTube video ID
    vimeo: # Vimeo video ID
```
