### ISSUE TITLE
Supaplex Game Remake

### ISSUE THREAD

**Issue by eguneys** [opengaming/osgameclones#719]
New game

```yaml
- name: Supaplex
  type: remake
  originals: [http://www.elmerproductions.com/sp/links.html]
  repo: https://github.com/eguneys/supaxl
  url: https://eguneys.github.io/jsgames/
  feed:
  development: sporadic
  status: playable
  multiplayer: [Local]
  lang: [html5, javascript]
  framework: [pixi.js]
  license: [MIT]
  content: open
  info: Play supaplex clone
  updated: 20 Dec 2018
  images:
    -
  video:
    youtube:
    vimeo:
```
