### ISSUE TITLE
Corrections for Jazz² Resurrection

### ISSUE THREAD

**Issue by deathkiller** [opengaming/osgameclones#738]
Corrected name of `Jazz² Resurrection`, listed as `Jazz 2 Resurrection`. Also updated the rest of items (info, images, video...).

```yaml
- name: Jazz² Resurrection
  development: active
  framework:
  - OpenGL
  images:
  - https://raw.githubusercontent.com/deathkiller/jazz2/master/Docs/Screen2.gif
  info: Runs on Windows, Linux, macOS and Android.
  lang:
  - C#
  license:
  - GPL3
  multiplayer:
  - Online
  content: commercial
  originals:
  - Jazz Jackrabbit 2
  repo: https://github.com/deathkiller/jazz2
  status: playable
  type: remake
  updated: 2019-05-11
  url: http://deat.tk/jazz2/
  video:
    youtube: M794QHwfMXg
```
