### ISSUE TITLE
Enduro

### ISSUE THREAD

**Issue by rafaelcastrocouto** [opengaming/osgameclones#774]
New game
https://racascou.itch.io/enduro

```yaml
- name: Enduro Tribute
  type: remake
  originals: [Enduro]
  repo: https://github.com/rafaelcastrocouto/enduro
  url: https://racascou.itch.io/enduro
  development: complete
  status: playable
  lang: [HTML5, Javascript, CSS]
  license: MIT
  content: open
  info:
  updated: 5/19
  images:
    - https://img.itch.zone/aW1nLzIxMzUyMzgucG5n/original/DZBGLA.png
```
