### ISSUE TITLE
Powerslide

### ISSUE THREAD

**Issue by cisoun** [opengaming/osgameclones#776]
New game

```yaml
- name: PowerSlideRemake
  type: remake
  original: Powerslide (RatBag)
  repo: https://bitbucket.org/dm_999/powerslideremake
  url: https://www.moddb.com/mods/powerslideremake
  feed:
  development: active
  status: semi-playable
  multiplayer: yes
  lang: english
  framework: Ogre 1.9.0
  license:MIT License (MIT)
  content: commercial
  updated: 2019-01-13
  images: https://www.moddb.com/mods/powerslideremake/images
  videos: https://www.moddb.com/mods/powerslideremake/videos
```
