### ISSUE TITLE
New Game: WallBall (Jezzball clone)

### ISSUE THREAD

**Issue by trevorjay** [opengaming/osgameclones#780]
New game
https://github.com/plainsightcollection/plainsightcollection.github.io

WallBall is my Jezzball clone. There are many like it, but this one is mine.

```yaml
- name: WallBall
  type: clone
  originals: [JezzBall]
  repo: https://github.com/plainsightcollection/plainsightcollection.github.io
  url: http://montrose.is/games/
  feed:
  development: complete
  status: playable
  multiplayer: []
  lang: [Haxe]
  framework: [Starling]
  license:
  - GPL3
  content: open
  info: Besides being playable on the development website, the game is available as a bookmarklet that let's it masquerade as a pop-up ad on most commercial websites.
  updated: 2019-06-09
  images:
    - https://raw.githubusercontent.com/plainsightcollection/plainsightcollection.github.io/master/web/resources/jpg/20170813_wallball.jpg
  video:
    youtube: n9ALgxcTBU0
    vimeo: # Vimeo video ID
```
