### ISSUE TITLE
The Legend of Edgar

### ISSUE THREAD

**Issue by nekonomicon** [opengaming/osgameclones#800]
The Legend of Edgar is The Legend of Zelda clone.

```yaml
- name: The Legend of Edgar
  type: clone
  originals: [Legend of Zelda]
  repo: https://github.com/riksweeney/edgar
  url: https://www.parallelrealities.co.uk/games/edgar/
  feed: https://www.parallelrealities.co.uk/rss.xml
  development: active
  status: playable
  lang: [C]
  framework: [SDL2]
  license: GPLv2+
  content: open
  info: The Legend of Edgar is a platform game, not unlike those found on the Amiga and SNES. Edgar must battle his way across the world, solving puzzles and defeating powerful enemies to achieve his quest. 
  updated: 2019-06-22
  images:
    - https://www.parallelrealities.co.uk/images/edgar/01.png
    - https://www.parallelrealities.co.uk/images/edgar/02.png
    - https://www.parallelrealities.co.uk/images/edgar/03.png
    - https://www.parallelrealities.co.uk/images/edgar/04.png
  video:
    youtube: https://youtu.be/3y_GEXdkVck
```
