### ISSUE TITLE
Gweled

### ISSUE THREAD

**Issue by bagok701** [opengaming/osgameclones#819]
New game

```yaml
- name: Gweled
  type: clone
  originals: [Bejeweled]
  repo: https://code.launchpad.net/gweled
  url: http://gweled.org/
  feed: http://feeds.launchpad.net/gweled/announcements.atom
  development: halted
  status: playable
  multiplayer: No
  lang: # many https://bazaar.launchpad.net/~dnax88/gweled/trunk/files/head:/po/
  framework: [GTK+]
  license: GPLv2
  content: open
  info: Gweled is a GTK+ version of a popular game "Bejeweled", originally written by Sebastien Delestaing. The aim of the game is to make alignment of 3 or more gems, both vertically or horizontally by swapping adjacent gems. The game ends when there are no possible moves left.
  updated: 2019-07-10
  images: [http://gweled.org/images/screen1.png, http://gweled.org/images/screen2.png, http://gweled.org/images/screen3.png] 
    -
  video:
    youtube: https://www.youtube.com/watch?v=fZ8NqKAVoUQ
```
