### ISSUE TITLE
Add OpenMB

### ISSUE THREAD

**Issue by cookgreen** [opengaming/osgameclones#829]
OpenMB

```yaml
- name: OpenMB
  type: remake
  originals: [Mount&Blade]
  repo: https://github.com/cookgreen/OpenMB
  url: https://www.indiedb.com/games/openmb
  development: active
  status: unplayable
  lang: [English, Simplified Chinese]
  framework: [Ogre3d]
  license: GPLv3
  content: commercial
  updated: 2019/07/22
```
