### ISSUE TITLE
Add Block Shooter

### ISSUE THREAD

**Issue by towerofglass** [opengaming/osgameclones#841]
```yaml
- name: Block Shooter
  type: clone
  originals: [Brick Shooter]
  repo: https://github.com/towerofglass/block-shooter
  url: https://towerofglass.github.io/block-shooter/
  development: complete
  status: playable
  lang: [English]
  framework: [phaserjs]
  license: MIT
  content: open
  info: remake of an old puzzle game
  updated: 2019/08/03
```
