### ISSUE TITLE
Add Magical Life

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#847]
New game

```yaml
- name: Magical Life
  type: similar
  originals:
  - Rimworld
  repo: https://github.com/SneakyTactician/MagicalLife
  development: sporadic
  status: semi-playable
  lang:
  - C#
  framework:
  - MonoGame
  license:
  - MIT
  content: open
  info: A fantasy world that imagines what a Rimworld style game could truly do if it had more elements in common with an RPG.
  updated: 2019-08-07
  video:
    youtube: NV8WLheFxtM
```
