### ISSUE TITLE
ZED Online

### ISSUE THREAD

**Issue by scratch85** [opengaming/osgameclones#858]
New game

```yaml
- name: ZED Online
  type: remake
  originals:
  - Z
  repo:
  url: http://zzone.lewe.com/
  feed:
  development: active
  status: playable
  lang:
  - C++
  framework:
  - # e.g. Unity, SDL2
  license: https://sourceforge.net/directory/license:gplv3/
  content: free
```
