### ISSUE TITLE
Add OpenMW for Android

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#897]
New game

```yaml
- name: OpenMW for Android
  type: remake
  originals:
  - The Elder Scrolls III: Morrowind
  repo: https://github.com/xyzz/openmw-android
  url: https://omw.xyz.is/
  development: active
  status: playable
  lang:
  - Kotlin
  license:
  - GPL3
  content: commercial
  updated: 2019-09-20
  video:
    youtube: E5VuN3d1fOM
```
