### ISSUE TITLE
Add openbor

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#899]
```yaml
- name: OpenBOR
  type:  clone
  originals:
  - Streets of Rage
  - Double Dragon
  - Final Fight
  repo: https://github.com/DCurrent/openbor
  url: http://www.chronocrash.com/forum/
  development: sporadic
  status: playable
  lang:
  - C
  framework:
  - SDL2
  license: BSD
  content: free
  info: OpenBOR is the ultimate 2D side scrolling engine for beat em' ups, shooters, and more!
  updated: 2019-09-23
  video:
    youtube: TbZD1pWsJeI
```
