### ISSUE TITLE
Add Cosmonium

### ISSUE THREAD

**Issue by Astuceman** [opengaming/osgameclones#907]
New game

```yaml
- name: Cosmonium
  type: similar
  originals: Space Engine
  - # Name of original
  repo: https://github.com/cosmonium/cosmonium
  url: https://github.com/cosmonium/cosmonium/wiki
  feed:
  development: active
  status: semi-playable
  multiplayer:
  - see: https://github.com/opengaming/osgameclones/blob/master/schema/games.yaml#L37
  lang: Python
  - # e.g. C++, JavaScript
  framework: Panda3D
  - # e.g. Unity, SDL2
  license: GPL3
  content: open
  info:
  updated: 2019-09-30
  images: https://raw.githubusercontent.com/wiki/cosmonium/cosmonium/screenshots/Io%2BJupiter.png
  - # image URL
  video:
    youtube: # YouTube video ID
    vimeo: # Vimeo video ID
```
