### ISSUE TITLE
Multiple wikipedia/external links for originals

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#954]
We've combined a few original games (e.g. doom + doom 2) to reduce duplication, but sometimes these games have unique wikipedia articles or external links. To reflect this, we should change the schema to allow wikipedia / external links per name.

e.g.

```yaml
- names:
  - name: Doom
    wikipedia: Doom
  - name: Doom II
    wikipedia: Doom II
  meta: ...
```
