### ISSUE TITLE
Add Road Rash

### ISSUE THREAD

**Issue by adrijshikhar** [opengaming/osgameclones#973]
New game

```yaml
- name:
  type: # One of: remake, clone, similar, tool
  originals:
  - # Name of original
  repo:
  url:
  feed:
  development: # One of: complete, very active, active, sporadic, halted
  status: # One of: playable, semi-playable, unplayable
  multiplayer:
  - see: https://github.com/opengaming/osgameclones/blob/master/schema/games.yaml#L37
  lang:
  - # e.g. C++, JavaScript
  framework:
  - # e.g. Unity, SDL2
  license: # see: https://github.com/opengaming/osgameclones/blob/master/schema/games.yaml#L72
  content: # One of: commercial, free, open, swappable
  info:
  updated: # insert current date as YYYY-MM-DD
  images:
  - # image URL
  video:
    youtube: # YouTube video ID
    vimeo: # Vimeo video ID
```
